export { default as Dark } from './Dark.svelte'
export { default as Koridor } from './Koridor.svelte'
export { default as Light } from './Light.svelte'
export { default as Local2 } from './Local2.svelte'
export { default as Local4 } from './Local4.svelte'
